### ISSUE TITLE
Get Api key information missing

### ISSUE THREAD

**Issue by maheshj01** [kiwicopple/sheet-metal#19]
Thanks for this amazing project, I tried to give it a shot but unfortunately, I couldn't find a way to get the Sheet metal API key, 
I tried selecting different pricing plans but it seems the site is missing this info.
Also, the site talks about the sheet Metal Api dashboard but there's no way we could navigate to it.

**Comment by kiwicopple** [comment]
hey @maheshmnj - this one is no longer maintained as I'm busy with Supabase. sorry :(

**Comment by maheshj01** [comment]
Sure no problem no doubt superbase is promising.
